server:
  port: 8090

template:
  templates:
    - {"templateId":"1","templateFilePath":"C:/allProjects/kafka_study/src/main/resources/template/template.json","active": true}
    - {"templateId":"2","templateFilePath":"C:/allProjects/kafka_study/src/main/resources/template/template.json","active": false}
  template-result-type: 0 # 0 - 文件获取； 1-数据库获取； 2- 其它
  template-result-file-path: "C:/allProjects/kafka_study/src/main/resources/template/templateResult.json"

wechat:
  kafka:
    bootstrap_servers: "192.168.1.252:9092"
    acks_config: "all"
    partitioner_class: "com.imooc.guilin.kafka.producer.SamplePartition"

#logging:
#  config: classpath:logback.xml